"""empty message

Revision ID: 44150e4b1936
Revises: 59f59180f8de
Create Date: 2016-01-26 15:26:19.495037

"""

# revision identifiers, used by Alembic.
revision = '44150e4b1936'
down_revision = '59f59180f8de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_folds', sa.Column('full_train_predictions', sa.Text(), nullable=True))
    op.add_column('submission_folds', sa.Column('test_predictions', sa.Text(), nullable=True))
    op.drop_column('submission_folds', 'predictions')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_folds', sa.Column('predictions', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('submission_folds', 'test_predictions')
    op.drop_column('submission_folds', 'full_train_predictions')
    ### end Alembic commands ###
