"""empty message

Revision ID: 59f59180f8de
Revises: adc5189810fb
Create Date: 2016-01-26 15:02:42.575974

"""

# revision identifiers, used by Alembic.
revision = '59f59180f8de'
down_revision = 'adc5189810fb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_folds', sa.Column('train_cpu_time', sa.Float(), nullable=True))
    op.add_column('submission_folds', sa.Column('train_memory', sa.Float(), nullable=True))
    op.add_column('submission_folds', sa.Column('train_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_folds', 'train_time')
    op.drop_column('submission_folds', 'train_memory')
    op.drop_column('submission_folds', 'train_cpu_time')
    ### end Alembic commands ###
