"""empty message

Revision ID: a5d75457442b
Revises: 44150e4b1936
Create Date: 2016-01-26 16:33:02.339439

"""

# revision identifiers, used by Alembic.
revision = 'a5d75457442b'
down_revision = '44150e4b1936'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submission_folds', sa.Column('test_time', sa.Float(), nullable=True))
    op.add_column('submission_folds', sa.Column('validation_time', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submission_folds', 'validation_time')
    op.drop_column('submission_folds', 'test_time')
    ### end Alembic commands ###
