# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0002_auto_20160203_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='name',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
