# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0003_auto_20160204_0910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='databoard_id',
            new_name='databoard_s_id',
        ),
        migrations.RenameField(
            model_name='submissionfold',
            old_name='databoard_id',
            new_name='databoard_sf_id',
        ),
    ]
