# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0005_auto_20160205_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfold',
            name='submission',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='runapp.Submission'),
        ),
    ]
