# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-07 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0006_auto_20160207_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submissionfold',
            old_name='submission',
            new_name='databoard_s',
        ),
    ]
