# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-08 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0007_auto_20160207_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfold',
            name='databoard_s',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runapp.Submission'),
        ),
    ]
