"""empty message

Revision ID: 2ac796bbb84f
Revises: e1dc9db4bdca
Create Date: 2016-01-23 23:37:31.670509

"""

# revision identifiers, used by Alembic.
revision = '2ac796bbb84f'
down_revision = 'e1dc9db4bdca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('files_path', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('files_path', sa.String(length=200), nullable=True),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_folds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('train_is', sa.LargeBinary(), nullable=False),
    sa.Column('test_is', sa.LargeBinary(), nullable=False),
    sa.Column('predictions', sa.LargeBinary(), nullable=True),
    sa.Column('state', sa.Enum('todo', 'done', 'error', name='state'), nullable=True),
    sa.Column('log_messages', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_folds')
    op.drop_table('submission')
    op.drop_table('raw_data')
    ### end Alembic commands ###
