"""empty message

Revision ID: d9308098a7d7
Revises: 24b11e7899b0
Create Date: 2016-01-20 17:50:09.565079

"""

# revision identifiers, used by Alembic.
revision = 'd9308098a7d7'
down_revision = '24b11e7899b0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('name', sa.String(length=40), nullable=False))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_data', 'name')
    ### end Alembic commands ###
