"""empty message

Revision ID: e1dc9db4bdca
Revises: d9308098a7d7
Create Date: 2016-01-20 18:03:34.946411

"""

# revision identifiers, used by Alembic.
revision = 'e1dc9db4bdca'
down_revision = 'd9308098a7d7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('files_path', sa.String(length=200), nullable=True))
    op.drop_column('raw_data', 'file_path')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('raw_data', sa.Column('file_path', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_column('raw_data', 'files_path')
    ### end Alembic commands ###
