# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-03 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('files_path', models.CharField(max_length=200, null=True)),
                ('workflow_elements', models.CharField(max_length=200)),
                ('target_column', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('databoard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('files_path', models.CharField(max_length=200, null=True)),
                ('raw_data', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runapp.RawData')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionFold',
            fields=[
                ('databoard_id', models.IntegerField(primary_key=True, serialize=False)),
                ('train_is', models.TextField()),
                ('test_is', models.TextField()),
                ('full_train_predictions', models.TextField()),
                ('test_predictions', models.TextField()),
                ('state', models.CharField(choices=[('TODO', 'to be trained'), ('TRAINED', 'trained'), ('VALIDATED', 'trained and validated'), ('TESTED', 'trained, validated, and tested'), ('ERROR', 'error during the train or test')], default='TODO', max_length=10)),
                ('log_messages', models.TextField()),
                ('train_time', models.FloatField(default=0.0, null=True)),
                ('validation_time', models.FloatField(default=0.0, null=True)),
                ('test_time', models.FloatField(default=0.0, null=True)),
                ('train_cpu_time', models.FloatField(default=0.0, null=True)),
                ('train_memory', models.FloatField(default=0.0, null=True)),
                ('submission_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='runapp.Submission')),
            ],
        ),
    ]
