# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0004_auto_20160205_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissionfold',
            name='full_train_predictions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submissionfold',
            name='log_messages',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='submissionfold',
            name='state',
            field=models.CharField(choices=[('TODO', 'to be trained'), ('TRAINED', 'trained'), ('VALIDATED', 'trained and validated'), ('TESTED', 'trained, validated, and tested'), ('ERROR', 'error during the train or test')], default='TODO', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='submissionfold',
            name='test_predictions',
            field=models.TextField(null=True),
        ),
    ]
