# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0008_auto_20160208_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfold',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
