# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0009_submissionfold_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionfold',
            name='priority',
            field=models.CharField(choices=[('low', 'low priority'), ('high', 'high priority')], default='low', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='submissionfold',
            name='test_cpu_time',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='submissionfold',
            name='test_memory',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
