# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0011_submissionfold_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='hash_files',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
