# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-30 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0012_submission_hash_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hash_files',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
