# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-31 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runapp', '0013_auto_20160530_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='hash_files',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
